[package]
name = "aoc-23-rs"
version = "0.0.1"
edition = "2021"

[dependencies]
nom = "7.1.3"

[[bin]]
name = "day"
path = "day_3.rs"

[lib]
name = "aoclib_rs"
path = "aoc.rs"

[profile.release]
debug = 1
